### ISSUE TITLE
There is nothing in the list of branches except the master

### ISSUE THREAD

**Issue by vhar** [CDTRSFE/gitlab-mrt#1]
Cannot create a merge request because only the master is listed in the branches
Gitlab Mrt v0.1.5
VSCode 1.63.2
Linux Mint 20.2 Cinnamon kernel 5.4.0-96-generic

GitLab Community Edition 14.5.0

![490](https://user-images.githubusercontent.com/5484416/151872392-aacc4262-f508-4b8f-ad4f-f09ae915501d.png)

**Comment by izhaoqing** [comment]
click the refresh button in the upper right corner to update the branch list.
